version: '3.8'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: ./services/app
    expose: 
      - 5001
    ports:
      - 8081:8081
    env_file:
      ./.env
    volumes:
      - ./services/app/data:/home/app/data
      - ./services/app/img:/home/app/img
      - ./services/app/logs:/var/log
      - ./services/app/page_source:/home/app/page_source
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_bonds:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    expose:
      - 5432
volumes:
  postgres_bonds: